School Library : Save Data
ometman/oop-school-library pull request #6
Opened 2023-11-30 12:41 UTC by Kwamay

In this milestone we ..........

- [ ] Save all data (books, people, and rentals) into JSON files. One per type of data you are storing and named accordingly (e.g. rentals.json)
- [ ] Loaded all data from files upon startup.

2023-11-30 13:09 UTC, julie-ify requested changes
## Hi @Kwamay and @ometman,

Good job so far!

## Highlights!
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-30 13:09 UTC, julie-ify commented on main.rb
> +  # JSON.parse(File.read(filename))
- [ ] Kindly remove commented code lines on lines 18, 26 and 34.

2023-11-30 13:09 UTC, julie-ify commented on main.rb
> +end
- [ ] When add data to the JSON files and quit, when I re-reun the app, and try to list the previously added data, they are listed as empty strings or "UNKNOWN" for the persons. Kindly rectify this. I believe it may have to the fact that your data is being saved as memory hashes, instead of the actual user data.

  This is how the data is being saved in the JSON files.
  ```
  ["#<Rental:0x00000289cf45cfd0>","#<Rental:0x00000289cf438f90>"]
  ["#<Book:0x00000289cf45e1f0>","#<Book:0x00000289cf45d980>","#<Book:0x00000289cf43ad90>"]
  ["#<Person:0x00000289cf453e30>","#<Person:0x00000289cf453228>","#<Student:0x00000289cf446b18>","#<Teacher:0x00000289cf4444d0>"]
  ```

  ![image](https://github.com/ometman/oop-school-library/assets/81468675/f7458537-dd1f-4c91-804d-d8f403a330f1)

2023-12-01 03:53 UTC, prolajumokeoni approved these changes
Hi @ometman 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
 - Added data is shown on rerun of app ✅ 
 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-01 08:17 UTC, merged